node:
  /move_group*
  /transform*
  /controller_manager
  /controller_stopper
  /rosapi*
  /servo*
topic:
  # Add topic patterns here if needed
parameter:
  /move_group*
  /moveit*
  /servo_node*
  /rosbridge*
  /robot_state_publisher*
  /rosapi
