node:
  /launch_ros*
  /move_group*
  /transform*
  /controller_manager
  /controller_stopper
  /rosapi*
  /servo*
topic:
  # Add topic patterns here if needed
parameter:
  /launch_ros*
  /rosbridge*
  /robot_state_publisher*
  /rosapi*
  /move_group*
  /moveit*
  /servo_node*
  *use_sim_time
  *qos_override*